module dymc_seg(
	clk,
	rst_n,
	en,
	seg_data,
	sel);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	input en;
	output [7:0] seg_data;
	output [2:0] sel;

	wire clk;
	wire rst_n;
	wire en;
	reg [7:0] seg_data;
	reg [2:0] sel;

	//----Code starts here: integrated by Robei-----
	parameter CNT_REFRESH=100;
	//parameter CNT_END=16666665; //for board
	parameter CNT_END=166; //for test
	
	reg[23:0] cnt_delay;
	reg div_clk;
	reg[10:0] cnt_refresh;
	reg refre_clk;
	
	always@(posedge clk or negedge rst_n)begin
			if(~rst_n)begin
					cnt_delay<=24'd0;
					div_clk<=1'b0;
			end
			else if(cnt_delay==CNT_END)begin
					cnt_delay<=24'd0;
					div_clk<=~div_clk;
			end
			else
					cnt_delay<=cnt_delay+1'b1;
	
	end
	
	always@(posedge clk or negedge rst_n)begin
			if(~rst_n)begin
					cnt_refresh<=11'd0;
					refre_clk<=1'b0;
			end
			else if(cnt_refresh==CNT_REFRESH)begin
					cnt_refresh<=11'd0;
					refre_clk<=~refre_clk;
			end
			else
					cnt_refresh<=cnt_refresh+1'b1;
	
	end
	
	reg[2:0] m;
	always@(posedge refre_clk or negedge rst_n)begin
			if(~rst_n)
					m<=3'd0;
			else if(m==3'd3)
					m<=3'd0;
			else
					m<=m+1'b1;
	end
	
	
	reg[3:0] i;
	
	always@(posedge div_clk or negedge rst_n)begin
			if(~rst_n)
					i<=4'd0;
			else if(i==4'd9)
					i<=4'd0;
			else
					i<=i+1'b1;
	end
	
	always@(i)begin
			case(i)
			4'd0: begin seg_data<=8'b0011_1111; end
			4'd1: begin seg_data<=8'b0000_0110; end
			4'd2: begin seg_data<=8'b0101_1011; end
			4'd3: begin seg_data<=8'b0100_1111; end
			4'd4: begin seg_data<=8'b0110_0110; end
			4'd5: begin seg_data<=8'b0110_1101; end
			4'd6: begin seg_data<=8'b0111_1101; end
			4'd7: begin seg_data<=8'b0000_0111; end
			4'd8: begin seg_data<=8'b0111_1111; end
			4'd9: begin seg_data<=8'b0110_1111; end
			default: seg_data<=8'b0011_1111; 
			endcase
	end
	
	always@(m)begin
			case(m)
			3'd0: begin sel<=3'b000; end
			3'd1: begin sel<=3'b001; end
			3'd2: begin sel<=3'b010; end
			3'd3: begin sel<=3'b011; end
			default: sel<=3'b111;
			endcase
	end
	
	
	
	
	
endmodule    //dymc_seg

