#This file is generated by Robei!
#Pin Assignment for Xilinx FPGA with Software Vivado.
set_property PACKAGE_PIN N18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W9 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN W16 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property PACKAGE_PIN T17 [get_ports seg_data[0]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_data[0]]
set_property PACKAGE_PIN U18 [get_ports seg_data[1]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_data[1]]
set_property PACKAGE_PIN G19 [get_ports seg_data[2]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_data[2]]
set_property PACKAGE_PIN H16 [get_ports seg_data[3]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_data[3]]
set_property PACKAGE_PIN G20 [get_ports seg_data[4]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_data[4]]
set_property PACKAGE_PIN D20 [get_ports seg_data[5]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_data[5]]
set_property PACKAGE_PIN F19 [get_ports seg_data[6]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_data[6]]
set_property PACKAGE_PIN G18 [get_ports seg_data[7]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_data[7]]
set_property PACKAGE_PIN V17 [get_ports sel[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sel[0]]
set_property PACKAGE_PIN T16 [get_ports sel[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sel[1]]
set_property PACKAGE_PIN U19 [get_ports sel[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sel[2]]




